# Generated by Django 4.0.3 on 2022-04-02 11:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumni',
            fields=[
                ('Alumni_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('LinkedIn', models.CharField(max_length=256)),
                ('Province', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Sub_District', models.CharField(max_length=50)),
                ('Postal_code', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('Company_num', models.IntegerField(max_length=13, primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
                ('Industry_sector', models.CharField(max_length=50)),
                ('Sector', models.CharField(max_length=50)),
                ('Province', models.CharField(max_length=50)),
                ('District', models.CharField(max_length=50)),
                ('Sub_District', models.CharField(max_length=50)),
                ('Postal_code', models.IntegerField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('Course_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Course_title', models.CharField(max_length=50)),
                ('Faculty', models.CharField(max_length=50)),
                ('Campus', models.CharField(max_length=10)),
                ('Credits', models.FloatField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('Role', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('Authority', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Sys_User',
            fields=[
                ('User_id', models.IntegerField(max_length=13, primary_key=True, serialize=False)),
                ('Username', models.CharField(max_length=50)),
                ('Identity_num', models.IntegerField(max_length=13)),
                ('Name', models.CharField(max_length=50)),
                ('Surname', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=256)),
                ('PhoneNumber', models.IntegerField(max_length=10)),
                ('Role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumTUapp.role')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('Job_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Department', models.CharField(max_length=50)),
                ('Job_title', models.CharField(max_length=50)),
                ('Start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('Alumni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumTUapp.alumni')),
                ('Company_num', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumTUapp.company')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('Education_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Degree', models.CharField(max_length=50)),
                ('Gpa', models.FloatField(max_length=4)),
                ('Educated_date', models.DateField()),
                ('Graduated_date', models.DateField()),
                ('Alumni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumTUapp.alumni')),
                ('Course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumTUapp.course')),
            ],
        ),
        migrations.AddField(
            model_name='alumni',
            name='User_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='AlumTUapp.sys_user'),
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('Achievement_id', models.IntegerField(max_length=10, primary_key=True, serialize=False)),
                ('Achievement_name', models.CharField(max_length=256)),
                ('Institute', models.CharField(max_length=50)),
                ('Date', models.DateField()),
                ('Alumni_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='AlumTUapp.alumni')),
            ],
        ),
    ]
