# Generated by Django 4.0.3 on 2022-04-14 06:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AlumTUapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='User_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='Sys_User',
        ),
    ]
