# Generated by Django 4.0.3 on 2022-04-21 05:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumTUapp', '0004_alumni_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='slug',
            field=models.SlugField(null=True),
        ),
    ]
