# Generated by Django 4.0.3 on 2022-04-21 05:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlumTUapp', '0005_alumni_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='alumni',
            name='slug',
        ),
    ]
