# Generated by Django 4.0.3 on 2022-04-22 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumTUapp', '0006_remove_alumni_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='Name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='alumni',
            name='Surname',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
