# Generated by Django 4.0.3 on 2022-04-25 04:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumTUapp', '0009_alumni_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alumni',
            name='LinkedIn',
            field=models.CharField(max_length=256, null=True),
        ),
    ]
