# Generated by Django 4.0.3 on 2022-04-29 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumTUapp', '0013_job_consent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='Consent',
            field=models.BooleanField(),
        ),
    ]
