# Generated by Django 4.0.3 on 2022-04-30 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumTUapp', '0015_rename_company_num_job_company_alumni_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='Industry_sector',
            field=models.CharField(choices=[('เกษตรและอุตสาหกรรมอาหาร', 'เกษตรและอุตสาหกรรมอาหาร'), ('สินค้าอุปโภคบริโภค', 'สินค้าอุปโภคบริโภค'), ('ธุรกิจการเงิน', 'ธุรกิจการเงิน'), ('สินค้าอุตสาหกรรม', 'สินค้าอุตสาหกรรม'), ('อสังหาริมทรัพย์และก่อสร้าง', 'อสังหาริมทรัพย์และก่อสร้าง'), ('ทรัพยากร', 'ทรัพยากร'), ('บริการ', 'บริการ'), ('เทคโนโลยี', 'เทคโนโลยี')], max_length=50),
        ),
    ]
