# Generated by Django 4.0.3 on 2022-04-30 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AlumTUapp', '0017_alter_company_sector'),
    ]

    operations = [
        migrations.RenameField(
            model_name='education',
            old_name='Course_id',
            new_name='Course',
        ),
    ]
