# Generated by Django 4.0.4 on 2022-05-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumTUapp', '0018_rename_course_id_education_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='achievement',
            name='Achievement_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='Alumni_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='PhoneNumber',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='Postal_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='company',
            name='Company_num',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='Postal_code',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='Course_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='education',
            name='Education_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='Job_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
