# Generated by Django 4.0.3 on 2022-05-08 07:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('AlumTUapp', '0019_alter_achievement_achievement_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personel',
            fields=[
                ('Personel_id', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50, null=True)),
                ('Surname', models.CharField(max_length=50, null=True)),
                ('Email', models.EmailField(blank=True, max_length=50, null=True)),
                ('User_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
