# Generated by Django 4.0.4 on 2022-05-08 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumTUapp', '0021_personel_personel_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='personel',
            name='personel_type',
            field=models.CharField(choices=[('officer', 'officer'), ('dean', 'dean')], default='none', max_length=50),
        ),
    ]
