# Generated by Django 4.0.4 on 2022-05-10 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumTUapp', '0027_alumni_student_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
        migrations.AlterField(
            model_name='alumni',
            name='District',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='Postal_code',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='Province',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='alumni',
            name='Sub_District',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='personel',
            name='Email',
            field=models.EmailField(default='none@gmail.com', max_length=50),
        ),
        migrations.AlterField(
            model_name='personel',
            name='Name',
            field=models.CharField(default='none', max_length=50),
        ),
        migrations.AlterField(
            model_name='personel',
            name='Surname',
            field=models.CharField(default='none', max_length=50),
        ),
    ]
