# Generated by Django 4.0.3 on 2022-04-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AlumTUapp', '0008_alumni_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='alumni',
            name='Address',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
